// Utility functions for document generation
// In a production app, this would use libraries like docx or pdfkit

export interface DocumentOptions {
  title: string
  content: string
  author?: string
  date?: Date
}

export function generateDocxContent(options: DocumentOptions): string {
  const { title, content, author = "SmartNotes", date = new Date() } = options

  return `
${title.toUpperCase()}

Generated by: ${author}
Date: ${date.toLocaleDateString()} ${date.toLocaleTimeString()}

---

${content}

---

Generated by SmartNotes - Speech-to-Notes Generator
  `.trim()
}

export function formatTranscript(transcript: string): string {
  return `TRANSCRIPT

${transcript}

Word Count: ${transcript.split(/\s+/).filter(Boolean).length}
Character Count: ${transcript.length}`
}

export function formatStructuredNotes(notes: string): string {
  return `STRUCTURED NOTES

${notes}

---
These notes were automatically generated using AI-powered summarization.
Please review for accuracy and completeness.`
}

export function formatMindmap(mindmapData: string): string {
  return `MINDMAP STRUCTURE

${mindmapData}

---
This mindmap represents the hierarchical structure of key concepts
and their relationships as extracted from the source content.`
}
